name: listuserwithfirebase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  image_picker: ^1.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
